on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environemnt"
        required:  true
        default: "staging"
        type: choice
        options:
          - staging
          - testing
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying the application....."
